server:
  port: 9000  # 9000번 포트로 실행

spring:
  application:
    name: gmc

  sql:
    init:
      platform: mysql

  datasource:
    url: jdbc:mysql://music.cp0opinjnevy.ap-northeast-2.rds.amazonaws.com/music
    # url 형식은 jdbc:mysql://RDS의 EndPoint/내부 DB 스키마명 입니다.
    username: music # 만약 따로 설정하지 않으셨다면 기본값은 admin 입니다
    password: joe2187135! # 비밀번호를 입력해주세요!
    driver-class-name: com.mysql.cj.jdbc.Driver

